#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

if [[ "$PUID" != 911 && "$PUID" != 911 ]]; then

    groupmod -o -g "$PGID" organizr
    usermod -o -u "$PUID" organizr

    echo "
    -----------------------------------------------
    PGID and PUID is set, updating user and files
    -----------------------------------------------
    User uid:    $(id -u organizr)
    User gid:    $(id -g organizr)
    -----------------------------------------------
    "
    find /var/www -print0 | xargs -P "$(nproc)" -I {} -0 chown -h organizr:organizr {}
fi

find /var/www/data -print0 | xargs -P "$(nproc)" -I {} -0 chown -h organizr:organizr {}
find /config -print0 | xargs -P "$(nproc)" -I {} -0 chown -h organizr:organizr {}
