#!/command/with-contenv bash
# shellcheck shell=bash

if [ -f "/var/www/data/config/config.php" ]; then
    sed -i "s/'branch' => '[^']*',/'branch' =\> '$(cat /var/www/Docker.txt)',/" /var/www/data/config/config.php
    sed -i "s/'commit' => '[^']*',/'commit' =\> '$(cat /var/www/Github.txt)',/" /var/www/data/config/config.php
fi
