#!/command/with-contenv bash
# shellcheck shell=bash

if [ -f "/config/www/organizr/data/config/config.php" ] && [ -e "/var/www/data/.empty" ]; then
    rm -f /var/www/data/.empty
    ln -s /config/www/organizr/data /var/www/data
elif [ -f "/config/www/organizr/data/config/config.php" ] && [ -e "/var/www/data/config/config.php" ]; then
    echo "/var/www/data/ contains an existing install, not symlinking /config/www/organizr/data/"
fi

if [ -f "/var/www/data/config/config.php" ]; then
    sed -i "s/'branch' => '[^']*',/'branch' =\> '$(cat /var/www/Docker.txt)',/" /var/www/data/config/config.php
    sed -i "s/'commit' => '[^']*',/'commit' =\> '$(cat /var/www/Github.txt)',/" /var/www/data/config/config.php
fi
