name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push-container:
    if: github.event_name != 'pull_request' && contains(github.ref, 'actions') != 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Create VARS
        id: vars
        run: |
          BRANCH=v2-develop
          VERSION=$(curl -sX GET https://api.github.com/repos/causefx/Organizr/commits/${BRANCH} | jq -r '.sha')
          echo "::set-output name=branch::${GITHUB_REF//refs\/heads\//}"
          echo "::set-output name=username::$(echo ${GITHUB_REPOSITORY} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=source::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_REF//refs\/heads\//}"
          echo "::set-output name=url::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/master/README.md"
          echo "::set-output name=tag::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'):${VERSION}"
          echo "::set-output name=tag_branch::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'):${GITHUB_REF//refs\/heads\//}"
          echo "::set-output name=tag_org::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'):${BRANCH}"
          echo "::set-output name=tag_latest::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'):latest"
          echo "::set-output name=orgver::${VERSION}"
          echo "::set-output name=orgbranch::${BRANCH}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.username }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |
            ghcr.io/${{ steps.vars.outputs.tag }}
            ghcr.io/${{ steps.vars.outputs.tag_branch }}
            ghcr.io/${{ steps.vars.outputs.tag_latest }}
          build-args: |
            VERSION=${{ steps.vars.outputs.orgver }}
            BRANCH=${{ steps.vars.outputs.orgbranch }}
          labels: |
            org.opencontainers.image.source=${{ steps.vars.outputs.source }}
            org.opencontainers.image.url=${{ steps.vars.outputs.url }}

